### ISSUE TITLE
main.cssとiconzen.jpgが読み込めていない

### ISSUE THREAD

**Issue by tecsoc** [madoreenu/portfolio#1]
imgのsrcが`/img/iconzen.jpg`のようになっていますが、`./img/iconzen.jpg`って感じに直してください。もしくは`img/iconzen.jpg`こうですね

cssの方も同様ですね

**Comment by madoreenu** [comment]
ありがとうございます
CSSの方はJekyllのyamlファイルの書き方がよくわからず今調べているところです。。
